spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/phone-book?createDatabaseIfNotExist=true
    username: root
    password: mariadbroot
    validationQuery: SELECT 1
  jpa:
    ddl-auto: update